name = "PreprocessingPipeline"
uuid = "f3b207a7-3b3b-4b3b-8b3b-3b3b3b3b3b3b"
authors = ["Usama Bin Tariq <usama.bin.tariq@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Statistics = "1.11.1"
