name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'

    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests with coverage
      run: julia --project=@. --code-coverage=user -e 'using Pkg; Pkg.test(coverage=true)'

    - name: Generate coverage report
      run: |
        julia -e 'using Pkg; Pkg.add("Coverage")'
        julia -e 'using Coverage; LCOV.writefile("coverage-lcov.info", process_folder())'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage-lcov.info
        fail_ci_if_error: false
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4

    #   - name: Set up Julia
    #     uses: julia-actions/setup-julia@v2
    #     with:
    #       version: '1'

    #   - uses: julia-actions/cache@v2

    #   - name: Install dependencies
    #     run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

    #   - name: Run tests with coverage
    #     run: julia --project=. --code-coverage=all -e 'using Pkg; Pkg.test()'

    #   - name: Generate coverage report
    #     run: julia --project=. -e 'using Coverage; cover = process_folder(); LCOV.writefile("coverage.lcov", cover)'

    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       files: ./coverage.lcov 
    #       fail_ci_if_error: false

