name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1.10"


      - uses: julia-actions/cache@v2

      - name: Build package 
        uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""  

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        env:
          PYTHON: ""  

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info  
          slug: n1developer-ubt/data-preprocessing-juml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  #   name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}  
  #   runs-on: ${{ matrix.os }}
  #   timeout-minutes: 60
  #   permissions:
  #     actions: write  
  #     contents: read
  #   strategy:
  #     fail-fast: false  
  #     matrix:
  #       version:
  #         - '1.10'  
  #       os:
  #         - ubuntu-latest  
  #       arch:
  #         - x64  
  #   steps:
  #     - uses: actions/checkout@v4  
  #     - uses: julia-actions/setup-julia@v2
  #       with:
  #         version: ${{ matrix.version }}   
  #         arch: ${{ matrix.arch }}
  #     - uses: julia-actions/cache@v2
  #     - uses: julia-actions/julia-buildpkg@v1
  #       env:
  #         PYTHON: ""  
  #     - uses: julia-actions/julia-runtest@v1
  #       env:
  #         PYTHON: ""  
  #     - uses: julia-actions/julia-processcoverage@v1
  #     - uses: codecov/codecov-action@v5
  #       with:
  #         files: lcov.info  
  #         slug: n1developer-ubt/data-preprocessing-juml
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         fail_ci_if_error: false
